name: Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docker-images/**/README.md"
      - ".github/workflows/docker-hub-description.yml"

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    name: Docker Hub Update
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: macabrequinox/zshbuntu
          short-description: "Your Ultimate Ubuntu Image with Zsh Magic!"
          readme-filepath: "./docker-images/zshbuntu/README.md"